apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APPLICATION_SERVICE_ACCOUNT}
  namespace: ${APPLICATION_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${KUBERNETES_APP_NAME}
    app.kubernetes.io/part-of: ${KUBERNETES_APP_NAME}
