apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${KUBERNETES_APP_NAME}-secrets
  namespace: ${APPLICATION_NAMESPACE}
spec:
  provider: aws

  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "${APPLICATION_SECRET_ARN}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "APP_NAME"
            objectAlias: "APP_NAME"
          - path: "APP_URL"
            objectAlias: "APP_URL"
          - path: "APP_ENV"
            objectAlias: "APP_ENV"
          - path: "DB_HOST"
            objectAlias: "DB_HOST"
          - path: "DB_PORT"
            objectAlias: "DB_PORT"
          - path: "DB_DATABASE"
            objectAlias: "DB_DATABASE"
          - path: "DB_USERNAME"
            objectAlias: "DB_USERNAME"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"

  secretObjects:
    - secretName: ${KUBERNETES_APP_NAME}-secrets
      type: Opaque
      data:
        - objectName: APP_NAME
          key: APP_NAME
        - objectName: APP_URL
          key: APP_URL
        - objectName: APP_ENV
          key: APP_ENV
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_DATABASE
          key: DB_DATABASE
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
